// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderRouter.Services.Store.Contexts;

#nullable disable

namespace OrderRouter.Services.Migrations
{
    [DbContext(typeof(OrderRouterDbContext))]
    partial class OrderRouterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("OrderRouter.Services.Store.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OrderRouter.Services.Store.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanMailOrder")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SatisfactionScore")
                        .HasColumnType("REAL");

                    b.Property<bool>("ServesAllZips")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("OrderRouter.Services.Store.Entities.SupplierCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId", "Category")
                        .IsUnique();

                    b.ToTable("SupplierCategories");
                });

            modelBuilder.Entity("OrderRouter.Services.Store.Entities.SupplierZipCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ZipCode");

                    b.HasIndex("SupplierId", "ZipCode")
                        .IsUnique();

                    b.ToTable("SupplierZipCodes");
                });

            modelBuilder.Entity("OrderRouter.Services.Store.Entities.SupplierCategory", b =>
                {
                    b.HasOne("OrderRouter.Services.Store.Entities.Supplier", "Supplier")
                        .WithMany("Categories")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("OrderRouter.Services.Store.Entities.SupplierZipCode", b =>
                {
                    b.HasOne("OrderRouter.Services.Store.Entities.Supplier", "Supplier")
                        .WithMany("ZipCodes")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("OrderRouter.Services.Store.Entities.Supplier", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("ZipCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
